name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If this is a security issue, please refer to our [security policy](../security/policy) instead.
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Feature '…' is not working properly. I expect '…' to happen, but '…' happens instead.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction instructions
      description: Please write the steps needed to reproduce the bug.
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment info
      description: Please specify what system you are using.
      placeholder: |
        - Package version
        - Browser(s) are you seeing the problem on
        - Device you are using and operating system
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please provide additional information about the problem here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/inpsyde/.github/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
