name: Feature request
description: Propose an idea for a feature or an enhancement
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem.
      placeholder: It is frustrated when […].
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the desired solution
      description: A clear and concise description of what you want to happen.
      placeholder: It would be better if […].
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe the alternatives that you have considered
      description: A clear and concise description of any alternative solutions or features you considered.
      placeholder: Optionally, it could work to do […].
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please provide additional information about the feature request here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/inpsyde/.github/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
